#!/usr/bin/env node
/*
SPDX-FileCopyrightText: 2026 Humdek, University of Bern
SPDX-License-Identifier: MPL-2.0
*/
/**
 * Sign a SelfHelp distribution release document (core/frontend/scheduler/worker).
 *
 * Unlike scripts/sign.mjs (which builds the canonical *plugin* payload), this
 * signs a whole release document: it strips any existing `security` block,
 * canonicalises the remainder (byte-identical to validate-unified.mjs /
 * @shm/registry / the manager fixture signer), Ed25519-signs it, and writes the
 * release back with a fresh `security` block:
 *
 *     { signature, keyId, signedPayloadSha256 }
 *
 * Key selection (same precedence as sign.mjs):
 *   --key <base64-64-byte-secret> + --key-id <id>     (production)
 *   SELFHELP_SIGNING_KEY + SELFHELP_SIGNING_KEY_ID
 *   (default) the DETERMINISTIC DEV key derived from the fixed seed
 *             'selfhelp-dev-registry-signing-key-v1', keyId
 *             'selfhelp-official-2026'. This is the same dev key the committed
 *             0.1.0 core/frontend releases + the manager fixtures use, so the
 *             signed-offline test/validation path works end-to-end. It is NOT a
 *             production key.
 *
 * Usage:
 *   node scripts/sign-release.mjs --input releases/scheduler/selfhelp-scheduler-0.1.0.json
 *   node scripts/sign-release.mjs --input <file> --out <file>
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { argv, env, exit, stderr } from 'node:process';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
// tweetnacl (NOT libsodium) is used for key derivation + signing so the
// deterministic dev key matches the committed trusted-keys public key, which
// was generated by the manager fixture signer (tweetnacl). libsodium's
// crypto_sign_seed_keypair derives a DIFFERENT key from the same seed; the
// verifier only needs interoperable Ed25519 verification, which works fine.
const nacl = require('tweetnacl');

const DEV_KEY_ID = 'selfhelp-official-2026';
const DEV_SEED_PHRASE = 'selfhelp-dev-registry-signing-key-v1';
const SECRET_KEY_BYTES = 64;

function parseArgs(rest) {
  const out = { _: [] };
  for (let i = 0; i < rest.length; i++) {
    const tok = rest[i];
    if (tok.startsWith('--')) {
      const k = tok.slice(2);
      const v = rest[i + 1] && !rest[i + 1].startsWith('--') ? rest[++i] : true;
      out[k] = v;
    } else {
      out._.push(tok);
    }
  }
  return out;
}

function canonicalStringify(value) {
  if (value === null) return 'null';
  if (typeof value === 'string') return JSON.stringify(value);
  if (typeof value === 'number') return JSON.stringify(value);
  if (typeof value === 'boolean') return value ? 'true' : 'false';
  if (Array.isArray(value)) return '[' + value.map(canonicalStringify).join(',') + ']';
  if (typeof value === 'object') {
    const keys = Object.keys(value).sort();
    return '{' + keys.map((k) => JSON.stringify(k) + ':' + canonicalStringify(value[k])).join(',') + '}';
  }
  throw new Error(`Unsupported value: ${typeof value}`);
}

function sha256Hex(s) {
  return createHash('sha256').update(Buffer.from(s, 'utf8')).digest('hex');
}

function resolveKey(args) {
  const keyB64 = args.key || env.SELFHELP_SIGNING_KEY;
  if (keyB64) {
    const keyId = args['key-id'] || env.SELFHELP_SIGNING_KEY_ID;
    if (!keyId) throw new Error('--key-id (or SELFHELP_SIGNING_KEY_ID) is required when a key is supplied.');
    const secretKey = new Uint8Array(Buffer.from(keyB64, 'base64'));
    if (secretKey.length !== SECRET_KEY_BYTES) {
      throw new Error(`Signing key must be ${SECRET_KEY_BYTES} bytes (got ${secretKey.length}).`);
    }
    return { secretKey, keyId };
  }
  // Deterministic dev key (offline test path).
  const seed = new Uint8Array(createHash('sha256').update(DEV_SEED_PHRASE).digest());
  const kp = nacl.sign.keyPair.fromSeed(seed);
  return { secretKey: kp.secretKey, keyId: args['key-id'] || DEV_KEY_ID };
}

const args = parseArgs(argv.slice(2));
try {
  if (!args.input) throw new Error('--input <release.json> is required.');
  const release = JSON.parse(readFileSync(args.input, 'utf8'));
  const clone = { ...release };
  delete clone.security;
  const payload = canonicalStringify(clone);
  const { secretKey, keyId } = resolveKey(args);
  const signature = nacl.sign.detached(new Uint8Array(Buffer.from(payload, 'utf8')), secretKey);
  const signed = {
    ...clone,
    security: {
      signature: Buffer.from(signature).toString('base64'),
      keyId,
      signedPayloadSha256: `sha256:${sha256Hex(payload)}`,
    },
  };
  const serialised = JSON.stringify(signed, null, 2) + '\n';
  const outPath = args.out || args.input;
  writeFileSync(outPath, serialised, 'utf8');
  stderr.write(`signed ${outPath} (${keyId})\n`);
} catch (err) {
  stderr.write(`sign-release.mjs: ${err instanceof Error ? err.message : String(err)}\n`);
  exit(1);
}
